services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "54321:5432"
    volumes:
     - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 
